# Generated by Selenium IDE
import pytest
import time
import json
import csv
from selenium import webdriver

from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRobotics():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_robotics(self):
    with open('test_data.csv', mode = 'r') as csv_file:
      csv_reader = csv.DictReader(csv_file)
      line_count = 0
      for row in csv_reader:
        if line_count == 0:
          print(f'Column names are {", ".join(row)}')
          line_count += 1

        self.driver.get("https://carnegierobotics.applytojob.com/apply/BjE7MVB8og/2020-Fall-Electrical-Engineer-Internship-Coop")
        self.driver.set_window_size(1296, 696)
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1)").click()
        self.driver.find_element(By.ID, "resumator-firstname-value").send_keys(f'{row["first_name"]}')
        time.sleep(2)
        self.driver.find_element(By.ID, "resumator-firstname-value").send_keys(f'{row["last_name"]}')
        time.sleep(2)
        self.driver.find_element(By.ID, "resumator-email-value").send_keys(f'{row["email"]}')
        time.sleep(2)
        self.driver.find_element(By.ID, "resumator-phone-value").send_keys(f'{row["phone"]}')
        time.sleep(2)
        self.driver.find_element(By.ID, "resumator-choose-upload").click()
        self.driver.find_element(By.ID, "resumator-resume-value").send_keys("C:/Users/mingr/Desktop/Careeo/Careeo_Code/SampleResumeECE2.pdf")

        '''"C:/Users/mingr/Desktop/Careeo/Careeo_Code/SampleResumeECE1.pdf"'''

        '''f'{row["file"]}'''
        time.sleep(2)
        self.driver.find_element(By.ID, "resumator-questionnaire-q699461").click()
        dropdown = self.driver.find_element(By.ID, "resumator-questionnaire-q699461")
        dropdown.find_element(By.XPATH, f"//option[. = '{row['grade']}']").click()
        time.sleep(2)
        line_count += 1
        print(f'Processed {line_count} applications.')

    '''self.driver.find_element(By.ID, "resumator-questionnaire-q699461").click()'''

