# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBbot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_bbot(self):
    self.driver.get("https://airtable.com/shrXHbCt4nTn3iTgu")
    self.driver.set_window_size(1280, 680)
    time.sleep(5)
    self.driver.find_element(By.ID, "61f50e47a41536095d8e1d1ffdea30b0").send_keys("Mingrui Yang")
    self.driver.find_element(By.ID, "8e5fef63163566a113e12aa9b3f23a14").send_keys("mingruiyang12@outlook.com")
    self.driver.find_element(By.ID, "9cd61022db8a0c8ed16b159773968d37").send_keys("(737) 529-6126")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".relative > .flex-auto").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p1:nth-child(2) .flex-auto").click()
    self.driver.find_element(By.CSS_SELECTOR, ".contentEditableTextbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".justify-center").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".fsp-select-labels").click()

