# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAppian():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_appian(self):
    self.driver.get("https://www.appian.com/careers/search/job/?gh_jid=1937729&job_name=cloud-software-engineer&location=mclean-virginia")
    self.driver.set_window_size(1296, 696)
    self.driver.switch_to.frame(3)
    self.driver.find_element(By.ID, "first_name").click()
    self.driver.find_element(By.ID, "first_name").send_keys("gg")
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(7) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(7)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(7)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "last_name").click()
    self.driver.find_element(By.ID, "last_name").send_keys("gg")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("gg")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("gg")
    self.driver.find_element(By.LINK_TEXT, "Attach").click()
  
